// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerAgent_CreateVM_FullMethodName        = "/agent.WorkerAgent/CreateVM"
	WorkerAgent_DeleteVM_FullMethodName        = "/agent.WorkerAgent/DeleteVM"
	WorkerAgent_StopVM_FullMethodName          = "/agent.WorkerAgent/StopVM"
	WorkerAgent_StartVM_FullMethodName         = "/agent.WorkerAgent/StartVM"
	WorkerAgent_GetVMStatus_FullMethodName     = "/agent.WorkerAgent/GetVMStatus"
	WorkerAgent_ConfigurePort_FullMethodName   = "/agent.WorkerAgent/ConfigurePort"
	WorkerAgent_RemovePort_FullMethodName      = "/agent.WorkerAgent/RemovePort"
	WorkerAgent_ConfigureTunnel_FullMethodName = "/agent.WorkerAgent/ConfigureTunnel"
	WorkerAgent_RemoveTunnel_FullMethodName    = "/agent.WorkerAgent/RemoveTunnel"
)

// WorkerAgentClient is the client API for WorkerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerAgentClient interface {
	// Compute
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error)
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error)
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error)
	GetVMStatus(ctx context.Context, in *GetVMStatusRequest, opts ...grpc.CallOption) (*VMStatusResponse, error)
	// Network
	ConfigurePort(ctx context.Context, in *ConfigurePortRequest, opts ...grpc.CallOption) (*ConfigurePortResponse, error)
	RemovePort(ctx context.Context, in *RemovePortRequest, opts ...grpc.CallOption) (*RemovePortResponse, error)
	ConfigureTunnel(ctx context.Context, in *ConfigureTunnelRequest, opts ...grpc.CallOption) (*ConfigureTunnelResponse, error)
	RemoveTunnel(ctx context.Context, in *RemoveTunnelRequest, opts ...grpc.CallOption) (*RemoveTunnelResponse, error)
}

type workerAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerAgentClient(cc grpc.ClientConnInterface) WorkerAgentClient {
	return &workerAgentClient{cc}
}

func (c *workerAgentClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVMResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVMResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVMResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) GetVMStatus(ctx context.Context, in *GetVMStatusRequest, opts ...grpc.CallOption) (*VMStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStatusResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_GetVMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) ConfigurePort(ctx context.Context, in *ConfigurePortRequest, opts ...grpc.CallOption) (*ConfigurePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurePortResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_ConfigurePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) RemovePort(ctx context.Context, in *RemovePortRequest, opts ...grpc.CallOption) (*RemovePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePortResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_RemovePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) ConfigureTunnel(ctx context.Context, in *ConfigureTunnelRequest, opts ...grpc.CallOption) (*ConfigureTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureTunnelResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_ConfigureTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerAgentClient) RemoveTunnel(ctx context.Context, in *RemoveTunnelRequest, opts ...grpc.CallOption) (*RemoveTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTunnelResponse)
	err := c.cc.Invoke(ctx, WorkerAgent_RemoveTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerAgentServer is the server API for WorkerAgent service.
// All implementations must embed UnimplementedWorkerAgentServer
// for forward compatibility.
type WorkerAgentServer interface {
	// Compute
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error)
	StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error)
	StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error)
	GetVMStatus(context.Context, *GetVMStatusRequest) (*VMStatusResponse, error)
	// Network
	ConfigurePort(context.Context, *ConfigurePortRequest) (*ConfigurePortResponse, error)
	RemovePort(context.Context, *RemovePortRequest) (*RemovePortResponse, error)
	ConfigureTunnel(context.Context, *ConfigureTunnelRequest) (*ConfigureTunnelResponse, error)
	RemoveTunnel(context.Context, *RemoveTunnelRequest) (*RemoveTunnelResponse, error)
	mustEmbedUnimplementedWorkerAgentServer()
}

// UnimplementedWorkerAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerAgentServer struct{}

func (UnimplementedWorkerAgentServer) CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedWorkerAgentServer) DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedWorkerAgentServer) StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedWorkerAgentServer) StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedWorkerAgentServer) GetVMStatus(context.Context, *GetVMStatusRequest) (*VMStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMStatus not implemented")
}
func (UnimplementedWorkerAgentServer) ConfigurePort(context.Context, *ConfigurePortRequest) (*ConfigurePortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigurePort not implemented")
}
func (UnimplementedWorkerAgentServer) RemovePort(context.Context, *RemovePortRequest) (*RemovePortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePort not implemented")
}
func (UnimplementedWorkerAgentServer) ConfigureTunnel(context.Context, *ConfigureTunnelRequest) (*ConfigureTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureTunnel not implemented")
}
func (UnimplementedWorkerAgentServer) RemoveTunnel(context.Context, *RemoveTunnelRequest) (*RemoveTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTunnel not implemented")
}
func (UnimplementedWorkerAgentServer) mustEmbedUnimplementedWorkerAgentServer() {}
func (UnimplementedWorkerAgentServer) testEmbeddedByValue()                     {}

// UnsafeWorkerAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerAgentServer will
// result in compilation errors.
type UnsafeWorkerAgentServer interface {
	mustEmbedUnimplementedWorkerAgentServer()
}

func RegisterWorkerAgentServer(s grpc.ServiceRegistrar, srv WorkerAgentServer) {
	// If the following call panics, it indicates UnimplementedWorkerAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerAgent_ServiceDesc, srv)
}

func _WorkerAgent_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_GetVMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).GetVMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_GetVMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).GetVMStatus(ctx, req.(*GetVMStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_ConfigurePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).ConfigurePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_ConfigurePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).ConfigurePort(ctx, req.(*ConfigurePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_RemovePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).RemovePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_RemovePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).RemovePort(ctx, req.(*RemovePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_ConfigureTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).ConfigureTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_ConfigureTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).ConfigureTunnel(ctx, req.(*ConfigureTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerAgent_RemoveTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).RemoveTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_RemoveTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).RemoveTunnel(ctx, req.(*RemoveTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerAgent_ServiceDesc is the grpc.ServiceDesc for WorkerAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.WorkerAgent",
	HandlerType: (*WorkerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVM",
			Handler:    _WorkerAgent_CreateVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _WorkerAgent_DeleteVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _WorkerAgent_StopVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _WorkerAgent_StartVM_Handler,
		},
		{
			MethodName: "GetVMStatus",
			Handler:    _WorkerAgent_GetVMStatus_Handler,
		},
		{
			MethodName: "ConfigurePort",
			Handler:    _WorkerAgent_ConfigurePort_Handler,
		},
		{
			MethodName: "RemovePort",
			Handler:    _WorkerAgent_RemovePort_Handler,
		},
		{
			MethodName: "ConfigureTunnel",
			Handler:    _WorkerAgent_ConfigureTunnel_Handler,
		},
		{
			MethodName: "RemoveTunnel",
			Handler:    _WorkerAgent_RemoveTunnel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent.proto",
}
