// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterHostRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegistrationToken string                 `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address           string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Capability        string                 `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`                                 // JSON-encoded capability
	StorageDomains    []string               `protobuf:"bytes,6,rep,name=storage_domains,json=storageDomains,proto3" json:"storage_domains,omitempty"`   // storage domain names or IDs
	Location          string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`                                     // location name or ID
	FabricIp          string                 `protobuf:"bytes,8,opt,name=fabric_ip,json=fabricIp,proto3" json:"fabric_ip,omitempty"`                     // IP for Geneve tunnel endpoints (overlay fabric)
	WorkerGrpcAddr    string                 `protobuf:"bytes,9,opt,name=worker_grpc_addr,json=workerGrpcAddr,proto3" json:"worker_grpc_addr,omitempty"` // address of this worker's WorkerService gRPC server (e.g. "host:9191")
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterHostRequest) Reset() {
	*x = RegisterHostRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostRequest) ProtoMessage() {}

func (x *RegisterHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostRequest.ProtoReflect.Descriptor instead.
func (*RegisterHostRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterHostRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *RegisterHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterHostRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterHostRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *RegisterHostRequest) GetStorageDomains() []string {
	if x != nil {
		return x.StorageDomains
	}
	return nil
}

func (x *RegisterHostRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RegisterHostRequest) GetFabricIp() string {
	if x != nil {
		return x.FabricIp
	}
	return ""
}

func (x *RegisterHostRequest) GetWorkerGrpcAddr() string {
	if x != nil {
		return x.WorkerGrpcAddr
	}
	return ""
}

type RegisterHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // assigned UUID
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHostResponse) Reset() {
	*x = RegisterHostResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostResponse) ProtoMessage() {}

func (x *RegisterHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostResponse.ProtoReflect.Descriptor instead.
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterHostResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterHostResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterHostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HostId            string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Resources         *ResourceReport        `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	RegistrationToken string                 `protobuf:"bytes,3,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetResources() *ResourceReport {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *HeartbeatRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ResourceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedVcpus     int32                  `protobuf:"varint,1,opt,name=used_vcpus,json=usedVcpus,proto3" json:"used_vcpus,omitempty"`
	UsedRamMb     int64                  `protobuf:"varint,2,opt,name=used_ram_mb,json=usedRamMb,proto3" json:"used_ram_mb,omitempty"`
	RunningVms    []*VMInfo              `protobuf:"bytes,3,rep,name=running_vms,json=runningVms,proto3" json:"running_vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReport) Reset() {
	*x = ResourceReport{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReport) ProtoMessage() {}

func (x *ResourceReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReport.ProtoReflect.Descriptor instead.
func (*ResourceReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceReport) GetUsedVcpus() int32 {
	if x != nil {
		return x.UsedVcpus
	}
	return 0
}

func (x *ResourceReport) GetUsedRamMb() int64 {
	if x != nil {
		return x.UsedRamMb
	}
	return 0
}

func (x *ResourceReport) GetRunningVms() []*VMInfo {
	if x != nil {
		return x.RunningVms
	}
	return nil
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Vcpus         int32                  `protobuf:"varint,3,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	RamMb         int64                  `protobuf:"varint,4,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *VMInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VMInfo) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VMInfo) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

// DiskSpec describes a block device to attach to a VM.
type DiskSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevicePath    string                 `protobuf:"bytes,1,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`                                                 // host-side block device (e.g. /dev/sdb), filled in by worker after Attach
	TargetDev     string                 `protobuf:"bytes,2,opt,name=target_dev,json=targetDev,proto3" json:"target_dev,omitempty"`                                                    // guest device name (e.g. "vda")
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                                                                       // storage protocol: "sim", "iscsi", "rbd"
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // protocol-specific parameters from ExportInfo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSpec) Reset() {
	*x = DiskSpec{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSpec) ProtoMessage() {}

func (x *DiskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSpec.ProtoReflect.Descriptor instead.
func (*DiskSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DiskSpec) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *DiskSpec) GetTargetDev() string {
	if x != nil {
		return x.TargetDev
	}
	return ""
}

func (x *DiskSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DiskSpec) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// PortSpec describes a network interface to attach to a VM.
type PortSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        string                 `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`             // OVS interfaceid / Logical_Switch_Port name
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // guest MAC address
	BridgeName    string                 `protobuf:"bytes,3,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"` // OVS bridge name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PortSpec) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *PortSpec) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *PortSpec) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

// CloudInitSpec contains cloud-init seed data for a VM.
type CloudInitSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	UserData      string                 `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	MetaData      string                 `protobuf:"bytes,3,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	NetworkConfig string                 `protobuf:"bytes,4,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInitSpec) Reset() {
	*x = CloudInitSpec{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInitSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInitSpec) ProtoMessage() {}

func (x *CloudInitSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInitSpec.ProtoReflect.Descriptor instead.
func (*CloudInitSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CloudInitSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CloudInitSpec) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *CloudInitSpec) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *CloudInitSpec) GetNetworkConfig() string {
	if x != nil {
		return x.NetworkConfig
	}
	return ""
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // UUID assigned by the compute orchestrator
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`             // VM name
	Vcpus         int32                  `protobuf:"varint,3,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	RamMb         int64                  `protobuf:"varint,4,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	Disks         []*DiskSpec            `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Ports         []*PortSpec            `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	CloudInit     *CloudInitSpec         `protobuf:"bytes,7,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVMRequest) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *CreateVMRequest) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *CreateVMRequest) GetDisks() []*DiskSpec {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *CreateVMRequest) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *CreateVMRequest) GetCloudInit() *CloudInitSpec {
	if x != nil {
		return x.CloudInit
	}
	return nil
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running" on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVMResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Disks         []*DiskSpec            `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"` // disks to detach
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMRequest) Reset() {
	*x = DeleteVMRequest{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMRequest) ProtoMessage() {}

func (x *DeleteVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMRequest.ProtoReflect.Descriptor instead.
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *DeleteVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteVMRequest) GetDisks() []*DiskSpec {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DeleteVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMResponse) Reset() {
	*x = DeleteVMResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMResponse) ProtoMessage() {}

func (x *DeleteVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMResponse.ProtoReflect.Descriptor instead.
func (*DeleteVMResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *StartVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StartVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMResponse) Reset() {
	*x = StartVMResponse{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMResponse) ProtoMessage() {}

func (x *StartVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMResponse.ProtoReflect.Descriptor instead.
func (*StartVMResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

type StopVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *StopVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMResponse) Reset() {
	*x = StopVMResponse{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMResponse) ProtoMessage() {}

func (x *StopVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMResponse.ProtoReflect.Descriptor instead.
func (*StopVMResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

type ForceStopVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceStopVMRequest) Reset() {
	*x = ForceStopVMRequest{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceStopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceStopVMRequest) ProtoMessage() {}

func (x *ForceStopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceStopVMRequest.ProtoReflect.Descriptor instead.
func (*ForceStopVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ForceStopVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ForceStopVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ForceStopVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceStopVMResponse) Reset() {
	*x = ForceStopVMResponse{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceStopVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceStopVMResponse) ProtoMessage() {}

func (x *ForceStopVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceStopVMResponse.ProtoReflect.Descriptor instead.
func (*ForceStopVMResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

type RebootVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootVMRequest) Reset() {
	*x = RebootVMRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootVMRequest) ProtoMessage() {}

func (x *RebootVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootVMRequest.ProtoReflect.Descriptor instead.
func (*RebootVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *RebootVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RebootVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RebootVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootVMResponse) Reset() {
	*x = RebootVMResponse{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootVMResponse) ProtoMessage() {}

func (x *RebootVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootVMResponse.ProtoReflect.Descriptor instead.
func (*RebootVMResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

type GetVMStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMStateRequest) Reset() {
	*x = GetVMStateRequest{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMStateRequest) ProtoMessage() {}

func (x *GetVMStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMStateRequest.ProtoReflect.Descriptor instead.
func (*GetVMStateRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *GetVMStateRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVMStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVMStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "running", "shutoff", "paused", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMStateResponse) Reset() {
	*x = GetVMStateResponse{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMStateResponse) ProtoMessage() {}

func (x *GetVMStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMStateResponse.ProtoReflect.Descriptor instead.
func (*GetVMStateResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *GetVMStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x0fcirrus.agent.v1\"\xac\x02\n" +
	"\x13RegisterHostRequest\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"capability\x18\x04 \x01(\tR\n" +
	"capability\x12'\n" +
	"\x0fstorage_domains\x18\x06 \x03(\tR\x0estorageDomains\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1b\n" +
	"\tfabric_ip\x18\b \x01(\tR\bfabricIp\x12(\n" +
	"\x10worker_grpc_addr\x18\t \x01(\tR\x0eworkerGrpcAddrJ\x04\b\x05\x10\x06\"e\n" +
	"\x14RegisterHostResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x99\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12=\n" +
	"\tresources\x18\x02 \x01(\v2\x1f.cirrus.agent.v1.ResourceReportR\tresources\x12-\n" +
	"\x12registration_token\x18\x03 \x01(\tR\x11registrationToken\"/\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x89\x01\n" +
	"\x0eResourceReport\x12\x1d\n" +
	"\n" +
	"used_vcpus\x18\x01 \x01(\x05R\tusedVcpus\x12\x1e\n" +
	"\vused_ram_mb\x18\x02 \x01(\x03R\tusedRamMb\x128\n" +
	"\vrunning_vms\x18\x03 \x03(\v2\x17.cirrus.agent.v1.VMInfoR\n" +
	"runningVms\"b\n" +
	"\x06VMInfo\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05vcpus\x18\x03 \x01(\x05R\x05vcpus\x12\x15\n" +
	"\x06ram_mb\x18\x04 \x01(\x03R\x05ramMb\"\xe0\x01\n" +
	"\bDiskSpec\x12\x1f\n" +
	"\vdevice_path\x18\x01 \x01(\tR\n" +
	"devicePath\x12\x1d\n" +
	"\n" +
	"target_dev\x18\x02 \x01(\tR\ttargetDev\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12=\n" +
	"\x06params\x18\x04 \x03(\v2%.cirrus.agent.v1.DiskSpec.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\bPortSpec\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vbridge_name\x18\x03 \x01(\tR\n" +
	"bridgeName\"\x8c\x01\n" +
	"\rCloudInitSpec\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\tuser_data\x18\x02 \x01(\tR\buserData\x12\x1b\n" +
	"\tmeta_data\x18\x03 \x01(\tR\bmetaData\x12%\n" +
	"\x0enetwork_config\x18\x04 \x01(\tR\rnetworkConfig\"\x88\x02\n" +
	"\x0fCreateVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05vcpus\x18\x03 \x01(\x05R\x05vcpus\x12\x15\n" +
	"\x06ram_mb\x18\x04 \x01(\x03R\x05ramMb\x12/\n" +
	"\x05disks\x18\x05 \x03(\v2\x19.cirrus.agent.v1.DiskSpecR\x05disks\x12/\n" +
	"\x05ports\x18\x06 \x03(\v2\x19.cirrus.agent.v1.PortSpecR\x05ports\x12=\n" +
	"\n" +
	"cloud_init\x18\a \x01(\v2\x1e.cirrus.agent.v1.CloudInitSpecR\tcloudInit\"?\n" +
	"\x10CreateVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"k\n" +
	"\x0fDeleteVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x05disks\x18\x03 \x03(\v2\x19.cirrus.agent.v1.DiskSpecR\x05disks\"\x12\n" +
	"\x10DeleteVMResponse\"9\n" +
	"\x0eStartVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x11\n" +
	"\x0fStartVMResponse\"8\n" +
	"\rStopVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x10\n" +
	"\x0eStopVMResponse\"=\n" +
	"\x12ForceStopVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x15\n" +
	"\x13ForceStopVMResponse\":\n" +
	"\x0fRebootVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x12\n" +
	"\x10RebootVMResponse\"<\n" +
	"\x11GetVMStateRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x12GetVMStateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state2\xc4\x01\n" +
	"\x11ControllerService\x12[\n" +
	"\fRegisterHost\x12$.cirrus.agent.v1.RegisterHostRequest\x1a%.cirrus.agent.v1.RegisterHostResponse\x12R\n" +
	"\tHeartbeat\x12!.cirrus.agent.v1.HeartbeatRequest\x1a\".cirrus.agent.v1.HeartbeatResponse2\xcc\x04\n" +
	"\rWorkerService\x12O\n" +
	"\bCreateVM\x12 .cirrus.agent.v1.CreateVMRequest\x1a!.cirrus.agent.v1.CreateVMResponse\x12O\n" +
	"\bDeleteVM\x12 .cirrus.agent.v1.DeleteVMRequest\x1a!.cirrus.agent.v1.DeleteVMResponse\x12L\n" +
	"\aStartVM\x12\x1f.cirrus.agent.v1.StartVMRequest\x1a .cirrus.agent.v1.StartVMResponse\x12I\n" +
	"\x06StopVM\x12\x1e.cirrus.agent.v1.StopVMRequest\x1a\x1f.cirrus.agent.v1.StopVMResponse\x12X\n" +
	"\vForceStopVM\x12#.cirrus.agent.v1.ForceStopVMRequest\x1a$.cirrus.agent.v1.ForceStopVMResponse\x12O\n" +
	"\bRebootVM\x12 .cirrus.agent.v1.RebootVMRequest\x1a!.cirrus.agent.v1.RebootVMResponse\x12U\n" +
	"\n" +
	"GetVMState\x12\".cirrus.agent.v1.GetVMStateRequest\x1a#.cirrus.agent.v1.GetVMStateResponseB(Z&github.com/tjst-t/cirrus/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_agent_proto_goTypes = []any{
	(*RegisterHostRequest)(nil),  // 0: cirrus.agent.v1.RegisterHostRequest
	(*RegisterHostResponse)(nil), // 1: cirrus.agent.v1.RegisterHostResponse
	(*HeartbeatRequest)(nil),     // 2: cirrus.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 3: cirrus.agent.v1.HeartbeatResponse
	(*ResourceReport)(nil),       // 4: cirrus.agent.v1.ResourceReport
	(*VMInfo)(nil),               // 5: cirrus.agent.v1.VMInfo
	(*DiskSpec)(nil),             // 6: cirrus.agent.v1.DiskSpec
	(*PortSpec)(nil),             // 7: cirrus.agent.v1.PortSpec
	(*CloudInitSpec)(nil),        // 8: cirrus.agent.v1.CloudInitSpec
	(*CreateVMRequest)(nil),      // 9: cirrus.agent.v1.CreateVMRequest
	(*CreateVMResponse)(nil),     // 10: cirrus.agent.v1.CreateVMResponse
	(*DeleteVMRequest)(nil),      // 11: cirrus.agent.v1.DeleteVMRequest
	(*DeleteVMResponse)(nil),     // 12: cirrus.agent.v1.DeleteVMResponse
	(*StartVMRequest)(nil),       // 13: cirrus.agent.v1.StartVMRequest
	(*StartVMResponse)(nil),      // 14: cirrus.agent.v1.StartVMResponse
	(*StopVMRequest)(nil),        // 15: cirrus.agent.v1.StopVMRequest
	(*StopVMResponse)(nil),       // 16: cirrus.agent.v1.StopVMResponse
	(*ForceStopVMRequest)(nil),   // 17: cirrus.agent.v1.ForceStopVMRequest
	(*ForceStopVMResponse)(nil),  // 18: cirrus.agent.v1.ForceStopVMResponse
	(*RebootVMRequest)(nil),      // 19: cirrus.agent.v1.RebootVMRequest
	(*RebootVMResponse)(nil),     // 20: cirrus.agent.v1.RebootVMResponse
	(*GetVMStateRequest)(nil),    // 21: cirrus.agent.v1.GetVMStateRequest
	(*GetVMStateResponse)(nil),   // 22: cirrus.agent.v1.GetVMStateResponse
	nil,                          // 23: cirrus.agent.v1.DiskSpec.ParamsEntry
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: cirrus.agent.v1.HeartbeatRequest.resources:type_name -> cirrus.agent.v1.ResourceReport
	5,  // 1: cirrus.agent.v1.ResourceReport.running_vms:type_name -> cirrus.agent.v1.VMInfo
	23, // 2: cirrus.agent.v1.DiskSpec.params:type_name -> cirrus.agent.v1.DiskSpec.ParamsEntry
	6,  // 3: cirrus.agent.v1.CreateVMRequest.disks:type_name -> cirrus.agent.v1.DiskSpec
	7,  // 4: cirrus.agent.v1.CreateVMRequest.ports:type_name -> cirrus.agent.v1.PortSpec
	8,  // 5: cirrus.agent.v1.CreateVMRequest.cloud_init:type_name -> cirrus.agent.v1.CloudInitSpec
	6,  // 6: cirrus.agent.v1.DeleteVMRequest.disks:type_name -> cirrus.agent.v1.DiskSpec
	0,  // 7: cirrus.agent.v1.ControllerService.RegisterHost:input_type -> cirrus.agent.v1.RegisterHostRequest
	2,  // 8: cirrus.agent.v1.ControllerService.Heartbeat:input_type -> cirrus.agent.v1.HeartbeatRequest
	9,  // 9: cirrus.agent.v1.WorkerService.CreateVM:input_type -> cirrus.agent.v1.CreateVMRequest
	11, // 10: cirrus.agent.v1.WorkerService.DeleteVM:input_type -> cirrus.agent.v1.DeleteVMRequest
	13, // 11: cirrus.agent.v1.WorkerService.StartVM:input_type -> cirrus.agent.v1.StartVMRequest
	15, // 12: cirrus.agent.v1.WorkerService.StopVM:input_type -> cirrus.agent.v1.StopVMRequest
	17, // 13: cirrus.agent.v1.WorkerService.ForceStopVM:input_type -> cirrus.agent.v1.ForceStopVMRequest
	19, // 14: cirrus.agent.v1.WorkerService.RebootVM:input_type -> cirrus.agent.v1.RebootVMRequest
	21, // 15: cirrus.agent.v1.WorkerService.GetVMState:input_type -> cirrus.agent.v1.GetVMStateRequest
	1,  // 16: cirrus.agent.v1.ControllerService.RegisterHost:output_type -> cirrus.agent.v1.RegisterHostResponse
	3,  // 17: cirrus.agent.v1.ControllerService.Heartbeat:output_type -> cirrus.agent.v1.HeartbeatResponse
	10, // 18: cirrus.agent.v1.WorkerService.CreateVM:output_type -> cirrus.agent.v1.CreateVMResponse
	12, // 19: cirrus.agent.v1.WorkerService.DeleteVM:output_type -> cirrus.agent.v1.DeleteVMResponse
	14, // 20: cirrus.agent.v1.WorkerService.StartVM:output_type -> cirrus.agent.v1.StartVMResponse
	16, // 21: cirrus.agent.v1.WorkerService.StopVM:output_type -> cirrus.agent.v1.StopVMResponse
	18, // 22: cirrus.agent.v1.WorkerService.ForceStopVM:output_type -> cirrus.agent.v1.ForceStopVMResponse
	20, // 23: cirrus.agent.v1.WorkerService.RebootVM:output_type -> cirrus.agent.v1.RebootVMResponse
	22, // 24: cirrus.agent.v1.WorkerService.GetVMState:output_type -> cirrus.agent.v1.GetVMStateResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
