// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: network.proto

package networkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchHostNetworkStateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HostId            string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	RegistrationToken string                 `protobuf:"bytes,2,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchHostNetworkStateRequest) Reset() {
	*x = WatchHostNetworkStateRequest{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchHostNetworkStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchHostNetworkStateRequest) ProtoMessage() {}

func (x *WatchHostNetworkStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchHostNetworkStateRequest.ProtoReflect.Descriptor instead.
func (*WatchHostNetworkStateRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *WatchHostNetworkStateRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *WatchHostNetworkStateRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

// HostNetworkStateUpdate wraps either a full snapshot or a delta update.
type HostNetworkStateUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// full=true: agent should replace all state with this snapshot.
	// full=false: agent should apply additions in state and process removals.
	Full bool `protobuf:"varint,1,opt,name=full,proto3" json:"full,omitempty"`
	// The state payload (full snapshot or additions for delta).
	State *HostNetworkState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// For delta updates: IDs/keys of removed items.
	RemovedPortIds       []string `protobuf:"bytes,3,rep,name=removed_port_ids,json=removedPortIds,proto3" json:"removed_port_ids,omitempty"`
	RemovedPolicyIds     []string `protobuf:"bytes,4,rep,name=removed_policy_ids,json=removedPolicyIds,proto3" json:"removed_policy_ids,omitempty"`
	RemovedDnsNames      []string `protobuf:"bytes,5,rep,name=removed_dns_names,json=removedDnsNames,proto3" json:"removed_dns_names,omitempty"`
	RemovedRemotePortIps []string `protobuf:"bytes,6,rep,name=removed_remote_port_ips,json=removedRemotePortIps,proto3" json:"removed_remote_port_ips,omitempty"`
	// Monotonically increasing version for ordering and staleness detection.
	Version       uint64 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostNetworkStateUpdate) Reset() {
	*x = HostNetworkStateUpdate{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostNetworkStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostNetworkStateUpdate) ProtoMessage() {}

func (x *HostNetworkStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostNetworkStateUpdate.ProtoReflect.Descriptor instead.
func (*HostNetworkStateUpdate) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *HostNetworkStateUpdate) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *HostNetworkStateUpdate) GetState() *HostNetworkState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *HostNetworkStateUpdate) GetRemovedPortIds() []string {
	if x != nil {
		return x.RemovedPortIds
	}
	return nil
}

func (x *HostNetworkStateUpdate) GetRemovedPolicyIds() []string {
	if x != nil {
		return x.RemovedPolicyIds
	}
	return nil
}

func (x *HostNetworkStateUpdate) GetRemovedDnsNames() []string {
	if x != nil {
		return x.RemovedDnsNames
	}
	return nil
}

func (x *HostNetworkStateUpdate) GetRemovedRemotePortIps() []string {
	if x != nil {
		return x.RemovedRemotePortIps
	}
	return nil
}

func (x *HostNetworkStateUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// HostNetworkState is the complete or partial network state for a single host.
type HostNetworkState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*PortState           `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	Policies      []*PolicyRule          `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	RemotePorts   []*RemotePort          `protobuf:"bytes,3,rep,name=remote_ports,json=remotePorts,proto3" json:"remote_ports,omitempty"`
	DnsRecords    []*DnsRecord           `protobuf:"bytes,4,rep,name=dns_records,json=dnsRecords,proto3" json:"dns_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostNetworkState) Reset() {
	*x = HostNetworkState{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostNetworkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostNetworkState) ProtoMessage() {}

func (x *HostNetworkState) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostNetworkState.ProtoReflect.Descriptor instead.
func (*HostNetworkState) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *HostNetworkState) GetPorts() []*PortState {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *HostNetworkState) GetPolicies() []*PolicyRule {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *HostNetworkState) GetRemotePorts() []*RemotePort {
	if x != nil {
		return x.RemotePorts
	}
	return nil
}

func (x *HostNetworkState) GetDnsRecords() []*DnsRecord {
	if x != nil {
		return x.DnsRecords
	}
	return nil
}

// PortState describes a local VM port on this host.
type PortState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        string                 `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName        string                 `protobuf:"bytes,3,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	NetworkId     string                 `protobuf:"bytes,4,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NetworkName   string                 `protobuf:"bytes,5,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	GroupId       string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,7,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	MacAddress    string                 `protobuf:"bytes,8,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`  // VM IP (the .1 in the /30 block)
	GatewayIp     string                 `protobuf:"bytes,10,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"` // Gateway IP (the .2 in the /30 block)
	Vni           int32                  `protobuf:"varint,11,opt,name=vni,proto3" json:"vni,omitempty"`                             // VXLAN Network Identifier for Geneve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortState) Reset() {
	*x = PortState{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortState) ProtoMessage() {}

func (x *PortState) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortState.ProtoReflect.Descriptor instead.
func (*PortState) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *PortState) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *PortState) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *PortState) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *PortState) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *PortState) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *PortState) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PortState) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *PortState) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *PortState) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PortState) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *PortState) GetVni() int32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

// PolicyRule describes an allow/deny rule between two groups.
type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	SrcGroupId    string                 `protobuf:"bytes,3,opt,name=src_group_id,json=srcGroupId,proto3" json:"src_group_id,omitempty"`
	DstGroupId    string                 `protobuf:"bytes,4,opt,name=dst_group_id,json=dstGroupId,proto3" json:"dst_group_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`               // "tcp", "udp", "icmp", "any"
	DstPort       int32                  `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"` // 0 means any port
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Action        string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"` // "allow" or "deny"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyRule) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyRule) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *PolicyRule) GetSrcGroupId() string {
	if x != nil {
		return x.SrcGroupId
	}
	return ""
}

func (x *PolicyRule) GetDstGroupId() string {
	if x != nil {
		return x.DstGroupId
	}
	return ""
}

func (x *PolicyRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PolicyRule) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *PolicyRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PolicyRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// RemotePort describes a VM port on another host that local VMs may communicate with.
type RemotePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	HostIp        string                 `protobuf:"bytes,4,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"` // Geneve tunnel endpoint (remote host address)
	Vni           int32                  `protobuf:"varint,5,opt,name=vni,proto3" json:"vni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePort) Reset() {
	*x = RemotePort{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePort) ProtoMessage() {}

func (x *RemotePort) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePort.ProtoReflect.Descriptor instead.
func (*RemotePort) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *RemotePort) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *RemotePort) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemotePort) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RemotePort) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *RemotePort) GetVni() int32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

// DnsRecord describes a DNS record for a VM within a network.
type DnsRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "vm-1.api.my-app.internal"
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	NetworkId     string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecord) Reset() {
	*x = DnsRecord{}
	mi := &file_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecord) ProtoMessage() {}

func (x *DnsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecord.ProtoReflect.Descriptor instead.
func (*DnsRecord) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

func (x *DnsRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DnsRecord) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DnsRecord) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\x11cirrus.network.v1\"f\n" +
	"\x1cWatchHostNetworkStateRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12-\n" +
	"\x12registration_token\x18\x02 \x01(\tR\x11registrationToken\"\xbc\x02\n" +
	"\x16HostNetworkStateUpdate\x12\x12\n" +
	"\x04full\x18\x01 \x01(\bR\x04full\x129\n" +
	"\x05state\x18\x02 \x01(\v2#.cirrus.network.v1.HostNetworkStateR\x05state\x12(\n" +
	"\x10removed_port_ids\x18\x03 \x03(\tR\x0eremovedPortIds\x12,\n" +
	"\x12removed_policy_ids\x18\x04 \x03(\tR\x10removedPolicyIds\x12*\n" +
	"\x11removed_dns_names\x18\x05 \x03(\tR\x0fremovedDnsNames\x125\n" +
	"\x17removed_remote_port_ips\x18\x06 \x03(\tR\x14removedRemotePortIps\x12\x18\n" +
	"\aversion\x18\a \x01(\x04R\aversion\"\x82\x02\n" +
	"\x10HostNetworkState\x122\n" +
	"\x05ports\x18\x01 \x03(\v2\x1c.cirrus.network.v1.PortStateR\x05ports\x129\n" +
	"\bpolicies\x18\x02 \x03(\v2\x1d.cirrus.network.v1.PolicyRuleR\bpolicies\x12@\n" +
	"\fremote_ports\x18\x03 \x03(\v2\x1d.cirrus.network.v1.RemotePortR\vremotePorts\x12=\n" +
	"\vdns_records\x18\x04 \x03(\v2\x1c.cirrus.network.v1.DnsRecordR\n" +
	"dnsRecords\"\xbf\x02\n" +
	"\tPortState\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x17\n" +
	"\avm_name\x18\x03 \x01(\tR\x06vmName\x12\x1d\n" +
	"\n" +
	"network_id\x18\x04 \x01(\tR\tnetworkId\x12!\n" +
	"\fnetwork_name\x18\x05 \x01(\tR\vnetworkName\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\a \x01(\tR\tgroupName\x12\x1f\n" +
	"\vmac_address\x18\b \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\n" +
	" \x01(\tR\tgatewayIp\x12\x10\n" +
	"\x03vni\x18\v \x01(\x05R\x03vni\"\xf7\x01\n" +
	"\n" +
	"PolicyRule\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12 \n" +
	"\fsrc_group_id\x18\x03 \x01(\tR\n" +
	"srcGroupId\x12 \n" +
	"\fdst_group_id\x18\x04 \x01(\tR\n" +
	"dstGroupId\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x19\n" +
	"\bdst_port\x18\x06 \x01(\x05R\adstPort\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\"\x90\x01\n" +
	"\n" +
	"RemotePort\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x17\n" +
	"\ahost_ip\x18\x04 \x01(\tR\x06hostIp\x12\x10\n" +
	"\x03vni\x18\x05 \x01(\x05R\x03vni\"N\n" +
	"\tDnsRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId2\x8c\x01\n" +
	"\x13NetworkStateService\x12u\n" +
	"\x15WatchHostNetworkState\x12/.cirrus.network.v1.WatchHostNetworkStateRequest\x1a).cirrus.network.v1.HostNetworkStateUpdate0\x01B*Z(github.com/tjst-t/cirrus/proto/networkpbb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_network_proto_goTypes = []any{
	(*WatchHostNetworkStateRequest)(nil), // 0: cirrus.network.v1.WatchHostNetworkStateRequest
	(*HostNetworkStateUpdate)(nil),       // 1: cirrus.network.v1.HostNetworkStateUpdate
	(*HostNetworkState)(nil),             // 2: cirrus.network.v1.HostNetworkState
	(*PortState)(nil),                    // 3: cirrus.network.v1.PortState
	(*PolicyRule)(nil),                   // 4: cirrus.network.v1.PolicyRule
	(*RemotePort)(nil),                   // 5: cirrus.network.v1.RemotePort
	(*DnsRecord)(nil),                    // 6: cirrus.network.v1.DnsRecord
}
var file_network_proto_depIdxs = []int32{
	2, // 0: cirrus.network.v1.HostNetworkStateUpdate.state:type_name -> cirrus.network.v1.HostNetworkState
	3, // 1: cirrus.network.v1.HostNetworkState.ports:type_name -> cirrus.network.v1.PortState
	4, // 2: cirrus.network.v1.HostNetworkState.policies:type_name -> cirrus.network.v1.PolicyRule
	5, // 3: cirrus.network.v1.HostNetworkState.remote_ports:type_name -> cirrus.network.v1.RemotePort
	6, // 4: cirrus.network.v1.HostNetworkState.dns_records:type_name -> cirrus.network.v1.DnsRecord
	0, // 5: cirrus.network.v1.NetworkStateService.WatchHostNetworkState:input_type -> cirrus.network.v1.WatchHostNetworkStateRequest
	1, // 6: cirrus.network.v1.NetworkStateService.WatchHostNetworkState:output_type -> cirrus.network.v1.HostNetworkStateUpdate
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
