// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: network.proto

package networkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkStateService_WatchHostNetworkState_FullMethodName = "/cirrus.network.v1.NetworkStateService/WatchHostNetworkState"
)

// NetworkStateServiceClient is the client API for NetworkStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NetworkStateService is called BY workers to receive network state updates.
// The controller computes per-host state and streams it to each worker.
type NetworkStateServiceClient interface {
	// WatchHostNetworkState opens a server-streaming RPC.
	// The first message is a full state snapshot (full=true).
	// Subsequent messages are deltas (full=false) with additions and removals.
	WatchHostNetworkState(ctx context.Context, in *WatchHostNetworkStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostNetworkStateUpdate], error)
}

type networkStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkStateServiceClient(cc grpc.ClientConnInterface) NetworkStateServiceClient {
	return &networkStateServiceClient{cc}
}

func (c *networkStateServiceClient) WatchHostNetworkState(ctx context.Context, in *WatchHostNetworkStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostNetworkStateUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkStateService_ServiceDesc.Streams[0], NetworkStateService_WatchHostNetworkState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchHostNetworkStateRequest, HostNetworkStateUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkStateService_WatchHostNetworkStateClient = grpc.ServerStreamingClient[HostNetworkStateUpdate]

// NetworkStateServiceServer is the server API for NetworkStateService service.
// All implementations must embed UnimplementedNetworkStateServiceServer
// for forward compatibility.
//
// NetworkStateService is called BY workers to receive network state updates.
// The controller computes per-host state and streams it to each worker.
type NetworkStateServiceServer interface {
	// WatchHostNetworkState opens a server-streaming RPC.
	// The first message is a full state snapshot (full=true).
	// Subsequent messages are deltas (full=false) with additions and removals.
	WatchHostNetworkState(*WatchHostNetworkStateRequest, grpc.ServerStreamingServer[HostNetworkStateUpdate]) error
	mustEmbedUnimplementedNetworkStateServiceServer()
}

// UnimplementedNetworkStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkStateServiceServer struct{}

func (UnimplementedNetworkStateServiceServer) WatchHostNetworkState(*WatchHostNetworkStateRequest, grpc.ServerStreamingServer[HostNetworkStateUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchHostNetworkState not implemented")
}
func (UnimplementedNetworkStateServiceServer) mustEmbedUnimplementedNetworkStateServiceServer() {}
func (UnimplementedNetworkStateServiceServer) testEmbeddedByValue()                             {}

// UnsafeNetworkStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkStateServiceServer will
// result in compilation errors.
type UnsafeNetworkStateServiceServer interface {
	mustEmbedUnimplementedNetworkStateServiceServer()
}

func RegisterNetworkStateServiceServer(s grpc.ServiceRegistrar, srv NetworkStateServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkStateService_ServiceDesc, srv)
}

func _NetworkStateService_WatchHostNetworkState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchHostNetworkStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworkStateServiceServer).WatchHostNetworkState(m, &grpc.GenericServerStream[WatchHostNetworkStateRequest, HostNetworkStateUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkStateService_WatchHostNetworkStateServer = grpc.ServerStreamingServer[HostNetworkStateUpdate]

// NetworkStateService_ServiceDesc is the grpc.ServiceDesc for NetworkStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cirrus.network.v1.NetworkStateService",
	HandlerType: (*NetworkStateServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchHostNetworkState",
			Handler:       _NetworkStateService_WatchHostNetworkState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "network.proto",
}
